<a href="https://colab.research.google.com/github/uyenphuong18406/Hands-On-Artificial-Intelligence-for-Banking/blob/master/raw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import json
import pandas as pd
import numpy as np

In [59]:
# reading the JSON data using json.load()
file = 'sample_data/sample.json'
with open(file) as f:
    shopee_json = json.load(f)

# covert into string
# data = json.dumps(shopee_json,indent=2)
# print(data)
# print('items\titemid\twelcome_package_info\tliked\trecommendation_info')
itemid_arr = []
name_arr = []
raw_discount_arr = []
liked_count_arr = []
recommendation_info_arr = []
price_arr = []
shopid_arr = []
historical_sold_arr = []

for item in shopee_json['items']:
  itemid = item['itemid']
  name = item['name']
  raw_discount = item['raw_discount']
  liked_count = item['liked_count']
  recommendation_info = item['recommendation_info']
  price = item['price']
  shopid = item['shopid']
  historical_sold = item['historical_sold']
  # print(itemid,welcome_package_info,liked,recommendation_info,price_max_before_discount)
  itemid_arr.append(itemid)
  name_arr.append(name)
  raw_discount_arr.append(raw_discount)
  liked_count_arr.append(liked_count)
  recommendation_info_arr.append(recommendation_info)
  price_arr.append(price)
  shopid_arr.append(shopid)
  historical_sold_arr.append(historical_sold)


df = pd.DataFrame()
df['itemid']=itemid_arr
df['name']=name_arr
df['raw_discount'] = raw_discount_arr
df['liked_count'] = liked_count_arr
# df['recommendation_info'] = recommendation_info_arr
df['price'] = price_arr
df['shopid'] = shopid_arr
df['historical_sold'] = historical_sold_arr
print((df['price'].dtype))
df

int64

       itemid  ... historical_sold
0  6007404027  ...             131
1  3772191141  ...             983
2  7970531948  ...             889
3  3118503371  ...            3039

[4 rows x 7 columns]

In [74]:
# import json
# from urllib.request import urlopen

# with urlopen("https://shopee.vn/api/v2/item/get?itemid=1382410146&shopid=71861331") as response:
#     source = response.read()

# data = json.loads(source)

# print(json.dumps(data, indent=2))

# usd_rates = dict()

# for item in data['list']['resources']:
#     name = item['resource']['fields']['name']
#     price = item['resource']['fields']['price']
#     usd_rates[name] = price

# print(50 * float(usd_rates['USD/INR']))

In [79]:
import requests
# https://shopee.vn/bazic.onee shop này nè
shopID="59180464"

url= "https://shopee.vn/api/v2/search_items/?by=pop&limit=30&match_id=" + shopID + "&newest=" + "1" + "&order=desc&page_type=shop&version=2"
url_header="https://shopee.vn/shop/"+shopID +"/search"

#url = 'https://shopee.tw/api/v2/search_items/?by=pop&limit=30&match_id=1819984&newest=0&order=desc&page_type=shop&shop_categoryids=9271157&version=2'

headers = {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0',
    'X-Requested-With': 'XMLHttpRequest',
    'Referer': url_header
}    

r = requests.get(url, headers=headers)

data = r.json()
# print(json.dumps(data['items'], indent=2))

#print(data['items'][0].keys())

# for item in data['items']:
    # print('name:', item['name'])
    # print('prince:', item['price'])
    # print('sold:', item['historical_sold'])
    # print('---')
    # print(item['price'])


itemid_arr = []
name_arr = []
rating_star_arr = []
liked_count_arr = []
recommendation_info_arr = []
price_arr = []
shopid_arr = []
historical_sold_arr = []

for item in data['items']:
  itemid = item['itemid']
  name = item['name']
  rating_star = item['item_rating']['rating_star']
  liked_count = item['liked_count']
  recommendation_info = item['recommendation_info']
  price = item['price']
  shopid = item['shopid']
  historical_sold = item['historical_sold']
  # print(itemid,welcome_package_info,liked,recommendation_info,price_max_before_discount)
  itemid_arr.append(itemid)
  name_arr.append(name)
  rating_star_arr.append(rating_star)
  liked_count_arr.append(liked_count)
  recommendation_info_arr.append(recommendation_info)
  price_arr.append(price)
  shopid_arr.append(shopid)
  historical_sold_arr.append(historical_sold)


df = pd.DataFrame()
df['itemid']=itemid_arr
df['name']=name_arr
df['rating_star'] = rating_star_arr
df['liked_count'] = liked_count_arr
# df['recommendation_info'] = recommendation_info_arr
df['price'] = price_arr
df['shopid'] = shopid_arr
df['historical_sold'] = historical_sold_arr
print((df['price'].dtype))
df

int64

         itemid  ... historical_sold
0    9735620633  ...             270
1    3478315767  ...             223
2    6484292366  ...             225
3    3054944700  ...             114
4    3186368593  ...             175
5    6080026295  ...             166
6    3892632430  ...              95
7    7585400156  ...             125
8    5889702427  ...              61
9    2935278873  ...             190
10   7278216495  ...             124
11   9111737111  ...             145
12   9017043467  ...             158
13   8769716942  ...              35
14   3059624388  ...              65
15  10402484039  ...              66
16   5245535460  ...             153
17  10204514247  ...              58
18  10307056622  ...              64
19   9611740114  ...              71
20  11509157881  ...              51
21   8333961034  ...              56
22   9077858793  ...              56
23   8962233920  ...              33
24   7878210686  ...              53
25   8768896091  ...              45
26   7493393608  ...              40
27   8211747813  ...              83
28   4807586315  ...             132
29   8163727385  ...              38

[30 rows x 7 columns]

In [77]:
import requests

shopID="59180464"

url= "https://shopee.vn/api/v2/search_items/?by=pop&limit=30&match_id=" + shopID + "&newest=" + "1" + "&order=desc&page_type=shop&version=2"
url_header="https://shopee.vn/shop/"+shopID +"/search"

#url = 'https://shopee.tw/api/v2/search_items/?by=pop&limit=30&match_id=1819984&newest=0&order=desc&page_type=shop&shop_categoryids=9271157&version=2'

headers = {
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0',
    'X-Requested-With': 'XMLHttpRequest',
    'Referer': url_header
}    

r = requests.get(url, headers=headers)

data = r.json()
# print(json.dumps(data['items'], indent=2))


# create json file
with open('bazic.json','w') as f:
  json.dump(data,f,indent=2)

#print(data['items'][0].keys())

# for item in data['items']:
    # print('name:', item['name'])
    # print('prince:', item['price'])
    # print('sold:', item['historical_sold'])
    # print('---')
    # print(item['price'])